using System;

// Token: 0x020001E4 RID: 484
public static class UberShaderKeywords
{
	// Token: 0x04000DB5 RID: 3509
	public const string STEREO_INSTANCING_ON = "STEREO_INSTANCING_ON";

	// Token: 0x04000DB6 RID: 3510
	public const string UNITY_SINGLE_PASS_STEREO = "UNITY_SINGLE_PASS_STEREO";

	// Token: 0x04000DB7 RID: 3511
	public const string STEREO_MULTIVIEW_ON = "STEREO_MULTIVIEW_ON";

	// Token: 0x04000DB8 RID: 3512
	public const string STEREO_CUBEMAP_RENDER_ON = "STEREO_CUBEMAP_RENDER_ON";

	// Token: 0x04000DB9 RID: 3513
	public const string _GLOBAL_ZONE_LIQUID_TYPE__WATER = "_GLOBAL_ZONE_LIQUID_TYPE__WATER";

	// Token: 0x04000DBA RID: 3514
	public const string _GLOBAL_ZONE_LIQUID_TYPE__LAVA = "_GLOBAL_ZONE_LIQUID_TYPE__LAVA";

	// Token: 0x04000DBB RID: 3515
	public const string _ZONE_LIQUID_SHAPE__CYLINDER = "_ZONE_LIQUID_SHAPE__CYLINDER";

	// Token: 0x04000DBC RID: 3516
	public const string _USE_TEXTURE = "_USE_TEXTURE";

	// Token: 0x04000DBD RID: 3517
	public const string USE_TEXTURE__AS_MASK = "USE_TEXTURE__AS_MASK";

	// Token: 0x04000DBE RID: 3518
	public const string _USE_WEATHER_MAP = "_USE_WEATHER_MAP";

	// Token: 0x04000DBF RID: 3519
	public const string _ALPHA_DETAIL_MAP = "_ALPHA_DETAIL_MAP";

	// Token: 0x04000DC0 RID: 3520
	public const string _WATER_EFFECT = "_WATER_EFFECT";

	// Token: 0x04000DC1 RID: 3521
	public const string _HEIGHT_BASED_WATER_EFFECT = "_HEIGHT_BASED_WATER_EFFECT";

	// Token: 0x04000DC2 RID: 3522
	public const string _ALPHATEST_ON = "_ALPHATEST_ON";

	// Token: 0x04000DC3 RID: 3523
	public const string _MAINTEX_ROTATE = "_MAINTEX_ROTATE";

	// Token: 0x04000DC4 RID: 3524
	public const string _UV_WAVE_WARP = "_UV_WAVE_WARP";

	// Token: 0x04000DC5 RID: 3525
	public const string _LIQUID_VOLUME = "_LIQUID_VOLUME";

	// Token: 0x04000DC6 RID: 3526
	public const string _LIQUID_CONTAINER = "_LIQUID_CONTAINER";

	// Token: 0x04000DC7 RID: 3527
	public const string _EMISSION = "_EMISSION";

	// Token: 0x04000DC8 RID: 3528
	public const string _EMISSION_USE_UV_WAVE_WARP = "_EMISSION_USE_UV_WAVE_WARP";

	// Token: 0x04000DC9 RID: 3529
	public const string _USE_DEFORM_MAP = "_USE_DEFORM_MAP";

	// Token: 0x04000DCA RID: 3530
	public const string _USE_DAY_NIGHT_LIGHTMAP = "_USE_DAY_NIGHT_LIGHTMAP";

	// Token: 0x04000DCB RID: 3531
	public const string _USE_TEX_ARRAY_ATLAS = "_USE_TEX_ARRAY_ATLAS";

	// Token: 0x04000DCC RID: 3532
	public const string _CRYSTAL_EFFECT = "_CRYSTAL_EFFECT";

	// Token: 0x04000DCD RID: 3533
	public const string _EYECOMP = "_EYECOMP";

	// Token: 0x04000DCE RID: 3534
	public const string _MOUTHCOMP = "_MOUTHCOMP";

	// Token: 0x04000DCF RID: 3535
	public const string _ALPHA_BLUE_LIVE_ON = "_ALPHA_BLUE_LIVE_ON";

	// Token: 0x04000DD0 RID: 3536
	public const string _GRID_EFFECT = "_GRID_EFFECT";

	// Token: 0x04000DD1 RID: 3537
	public const string _REFLECTIONS = "_REFLECTIONS";

	// Token: 0x04000DD2 RID: 3538
	public const string _REFLECTIONS_BOX_PROJECT = "_REFLECTIONS_BOX_PROJECT";

	// Token: 0x04000DD3 RID: 3539
	public const string _REFLECTIONS_USE_NORMAL_TEX = "_REFLECTIONS_USE_NORMAL_TEX";

	// Token: 0x04000DD4 RID: 3540
	public const string _VERTEX_ROTATE = "_VERTEX_ROTATE";

	// Token: 0x04000DD5 RID: 3541
	public const string _VERTEX_ANIM_FLAP = "_VERTEX_ANIM_FLAP";

	// Token: 0x04000DD6 RID: 3542
	public const string _VERTEX_ANIM_WAVE = "_VERTEX_ANIM_WAVE";

	// Token: 0x04000DD7 RID: 3543
	public const string _VERTEX_ANIM_WAVE_DEBUG = "_VERTEX_ANIM_WAVE_DEBUG";

	// Token: 0x04000DD8 RID: 3544
	public const string _VERTEX_LIGHTING = "_VERTEX_LIGHTING";

	// Token: 0x04000DD9 RID: 3545
	public const string _GRADIENT_MAP_ON = "_GRADIENT_MAP_ON";

	// Token: 0x04000DDA RID: 3546
	public const string _PARALLAX = "_PARALLAX";

	// Token: 0x04000DDB RID: 3547
	public const string _PARALLAX_AA = "_PARALLAX_AA";

	// Token: 0x04000DDC RID: 3548
	public const string _PARALLAX_PLANAR = "_PARALLAX_PLANAR";

	// Token: 0x04000DDD RID: 3549
	public const string _MASK_MAP_ON = "_MASK_MAP_ON";

	// Token: 0x04000DDE RID: 3550
	public const string _FX_LAVA_LAMP = "_FX_LAVA_LAMP";

	// Token: 0x04000DDF RID: 3551
	public const string _INNER_GLOW = "_INNER_GLOW";

	// Token: 0x04000DE0 RID: 3552
	public const string _STEALTH_EFFECT = "_STEALTH_EFFECT";

	// Token: 0x04000DE1 RID: 3553
	public const string _UV_SHIFT = "_UV_SHIFT";

	// Token: 0x04000DE2 RID: 3554
	public const string _TEXEL_SNAP_UVS = "_TEXEL_SNAP_UVS";

	// Token: 0x04000DE3 RID: 3555
	public const string _UNITY_EDIT_MODE = "_UNITY_EDIT_MODE";

	// Token: 0x04000DE4 RID: 3556
	public const string _GT_EDITOR_TIME = "_GT_EDITOR_TIME";

	// Token: 0x04000DE5 RID: 3557
	public const string _DEBUG_PAWN_DATA = "_DEBUG_PAWN_DATA";

	// Token: 0x04000DE6 RID: 3558
	public const string _COLOR_GRADE_PROTANOMALY = "_COLOR_GRADE_PROTANOMALY";

	// Token: 0x04000DE7 RID: 3559
	public const string _COLOR_GRADE_PROTANOPIA = "_COLOR_GRADE_PROTANOPIA";

	// Token: 0x04000DE8 RID: 3560
	public const string _COLOR_GRADE_DEUTERANOMALY = "_COLOR_GRADE_DEUTERANOMALY";

	// Token: 0x04000DE9 RID: 3561
	public const string _COLOR_GRADE_DEUTERANOPIA = "_COLOR_GRADE_DEUTERANOPIA";

	// Token: 0x04000DEA RID: 3562
	public const string _COLOR_GRADE_TRITANOMALY = "_COLOR_GRADE_TRITANOMALY";

	// Token: 0x04000DEB RID: 3563
	public const string _COLOR_GRADE_TRITANOPIA = "_COLOR_GRADE_TRITANOPIA";

	// Token: 0x04000DEC RID: 3564
	public const string _COLOR_GRADE_ACHROMATOMALY = "_COLOR_GRADE_ACHROMATOMALY";

	// Token: 0x04000DED RID: 3565
	public const string _COLOR_GRADE_ACHROMATOPSIA = "_COLOR_GRADE_ACHROMATOPSIA";

	// Token: 0x04000DEE RID: 3566
	public const string LIGHTMAP_ON = "LIGHTMAP_ON";

	// Token: 0x04000DEF RID: 3567
	public const string DIRLIGHTMAP_COMBINED = "DIRLIGHTMAP_COMBINED";

	// Token: 0x04000DF0 RID: 3568
	public const string INSTANCING_ON = "INSTANCING_ON";

	// Token: 0x04000DF1 RID: 3569
	public static readonly string[] namesArray = new string[]
	{
		"STEREO_INSTANCING_ON",
		"UNITY_SINGLE_PASS_STEREO",
		"STEREO_MULTIVIEW_ON",
		"STEREO_CUBEMAP_RENDER_ON",
		"_GLOBAL_ZONE_LIQUID_TYPE__WATER",
		"_GLOBAL_ZONE_LIQUID_TYPE__LAVA",
		"_ZONE_LIQUID_SHAPE__CYLINDER",
		"_USE_TEXTURE",
		"USE_TEXTURE__AS_MASK",
		"_USE_WEATHER_MAP",
		"_ALPHA_DETAIL_MAP",
		"_WATER_EFFECT",
		"_HEIGHT_BASED_WATER_EFFECT",
		"_ALPHATEST_ON",
		"_MAINTEX_ROTATE",
		"_UV_WAVE_WARP",
		"_LIQUID_VOLUME",
		"_LIQUID_CONTAINER",
		"_EMISSION",
		"_EMISSION_USE_UV_WAVE_WARP",
		"_USE_DEFORM_MAP",
		"_USE_DAY_NIGHT_LIGHTMAP",
		"_USE_TEX_ARRAY_ATLAS",
		"_CRYSTAL_EFFECT",
		"_EYECOMP",
		"_MOUTHCOMP",
		"_ALPHA_BLUE_LIVE_ON",
		"_GRID_EFFECT",
		"_REFLECTIONS",
		"_REFLECTIONS_BOX_PROJECT",
		"_REFLECTIONS_USE_NORMAL_TEX",
		"_VERTEX_ROTATE",
		"_VERTEX_ANIM_FLAP",
		"_VERTEX_ANIM_WAVE",
		"_VERTEX_ANIM_WAVE_DEBUG",
		"_VERTEX_LIGHTING",
		"_GRADIENT_MAP_ON",
		"_PARALLAX",
		"_PARALLAX_AA",
		"_PARALLAX_PLANAR",
		"_MASK_MAP_ON",
		"_FX_LAVA_LAMP",
		"_INNER_GLOW",
		"_STEALTH_EFFECT",
		"_UV_SHIFT",
		"_TEXEL_SNAP_UVS",
		"_UNITY_EDIT_MODE",
		"_GT_EDITOR_TIME",
		"_DEBUG_PAWN_DATA",
		"_COLOR_GRADE_PROTANOMALY",
		"_COLOR_GRADE_PROTANOPIA",
		"_COLOR_GRADE_DEUTERANOMALY",
		"_COLOR_GRADE_DEUTERANOPIA",
		"_COLOR_GRADE_TRITANOMALY",
		"_COLOR_GRADE_TRITANOPIA",
		"_COLOR_GRADE_ACHROMATOMALY",
		"_COLOR_GRADE_ACHROMATOPSIA",
		"LIGHTMAP_ON",
		"DIRLIGHTMAP_COMBINED",
		"INSTANCING_ON"
	};
}
