using System;
using System.Diagnostics;
using System.Reflection;
using System.Runtime.CompilerServices;
using System.Security;
using System.Security.Permissions;
using Fusion;
using Unity.Burst;

[assembly: AssemblyVersion("0.0.0.0")]
[assembly: NetworkAssemblyWeaved]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.New_00002DBE$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Add_00002DBF$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Sub_00002DC0$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Mul_00002DC1$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Div_00002DC2$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Unm_00002DC3$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Eq_00002DC4$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Dot_00002DC6$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Cross_00002DC7$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Project_00002DC8$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Length_00002DC9$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Normalize_00002DCA$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.SafeNormal_00002DCB$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Distance_00002DCC$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Lerp_00002DCD$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.Rotate_00002DCE$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.ZeroVector_00002DCF$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.Vec3Functions.OneVector_00002DD0$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.New_00002DD1$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Mul_00002DD2$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Eq_00002DD3$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromEuler_00002DD5$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.FromDirection_00002DD6$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.GetUpVector_00002DD7$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(Bindings.QuatFunctions.Euler_00002DD8$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.Index_00002DDB$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NewIndex_00002DDC$BurstDirectCall))]
[assembly: BurstCompiler.StaticTypeReinitAttribute(typeof(BurstClassInfo.NameCall_00002DDD$BurstDirectCall))]
[assembly: SecurityPermission(SecurityAction.RequestMinimum, SkipVerification = true)]
